services:
    apache:
        build:
            context: .
            dockerfile: apache.dockerfile
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
            - php
        restart: unless-stopped
    mysql:
        image: mariadb:10.5
        ports:
            - 3306:3306
        environment:
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_SECRET: secret
            MARIADB_DATABASE: laravel
            MARIADB_ROOT_PASSWORD: secret
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
            MARIADB_RANDOM_ROOT_PASSWORD: secret
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        build:
            context: .
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${UID:-1000}

        volumes:
            - ./src:/var/www/html
    composer:
        build:
            context: .
            dockerfile: composer.dockerfile
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
    npm:
        image: node:current-alpine
        volumes:
            - ./src:/var/www/html
        entrypoint: ['npm']
        working_dir: /var/www/html
    console:
        build:
            context: .
            dockerfile: php.dockerfile
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
        entrypoint: ['php', '/var/www/html/bin/console']
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
        depends_on:
            - mysql
            - php
