services:
    nginx:
        build:
            context: .
            dockerfile: nginx.prod.dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
            - php
        restart: unless-stopped
    php:
        build:
            context: .
            dockerfile: php.prod.dockerfile
        volumes:
            - ./src:/var/www/html
    assets:
        image: node:current-alpine
        volumes:
            - ./src:/var/www/html
        command:
            [
                '/bin/sh',
                '-c',
                'npm i && npm run production && npm prune --production',
            ]
        working_dir: /var/www/html
